name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LaTeX compilation
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: report.tex
