name: Build LaTeX document

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LaTeX compilation
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: report.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: built-pdf
        path: report.pdf
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: error-log
        path: report.log
